# Generated by Django 5.2.1 on 2025-07-24 10:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HealthCheck",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "service_name",
                    models.CharField(default="auth-service", max_length=100),
                ),
                ("status", models.CharField(default="healthy", max_length=20)),
                ("version", models.CharField(default="1.0.0", max_length=50)),
            ],
            options={
                "verbose_name": "Health Check",
                "verbose_name_plural": "Health Checks",
                "db_table": "health_checks",
            },
        ),
    ]
