# Generated by Django 5.2.1 on 2025-07-25 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blacklistedtoken",
            name="token",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="emailverificationtoken",
            name="token",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="passwordresettoken",
            name="token",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="refreshtoken",
            name="token",
            field=models.TextField(),
        ),
    ]
